server:
  port: 8080

spring:
  datasource:
    username: dbtrade
    password: tougu.123
    url: jdbc:mysql://10.20.28.185:3306/dbtrade?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : info